version: '3'
services:
  redis:
    container_name: casamagalhaes_redis
    build:
      context: .
      dockerfile: ./docker/redis/Dockerfile
    ports:
      - 6379:6379
    networks:
      casa:
        aliases:
          - redis
  mysql:
    container_name: casamagalhaes_mysql
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    env_file:
      - ./docker/mysql/.env
    ports:
      - 3306:3306
    networks:
      casa:
        aliases:
          - mysql
  api:
    container_name: casamagalhaes_api
    build:
      context: .
      dockerfile: ./docker/node-api/Dockerfile
    volumes:
      - /app/node_modules
      - ${PWD}:/app
    env_file:
      - ./docker/node-api/.env
      - ./docker/mysql/.env
      - ./docker/redis/.env
    ports:
      - 3000:3000
    networks:
      casa:
        aliases:
          - api
networks:
  casa: