version: '3'
services:
  # redis:
  #   container_name: casamagalhaes_redis
  #   build:
  #     context: .
  #     dockerfile: ./docker/redis/Dockerfile
  #   ports:
  #     - 6379:6379
  #   networks:
  #     casa:
  #       aliases:
  #         - redis
  mysql:
    container_name: casamagalhaes_mysql
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    env_file:
      - ./docker/mysql/.env
    ports:
      - 3306:3306
    networks:
      casa:
        aliases:
          - mysql
  # rabbitmq:
  #   build:
  #     context: .
  #     dockerfile: ./docker/rabbitmq/Dockerfile
  #   container_name: casamagalhaes_rabbitmq
  #   env_file:
  #     - ./docker/rabbitmq/.env
  #   ports:
  #     - 25672:25672
  #     - 4369:4369
  #     - 5671:5671
  #     - 5672:5672
  #   networks:
  #     casa:
  #       aliases:
  #         - rabbitmq
  api:
    container_name: casamagalhaes_api
    build:
      context: .
      dockerfile: ./docker/node-api/Dockerfile
    volumes:
      - /app/node_modules
      - ${PWD}:/app
    env_file:
      - ./docker/node-api/.env
      - ./docker/mysql/.env
      # - ./docker/rabbitmq/.env
      # - ./docker/redis/.env
    ports:
      - 3000:3000
    networks:
      casa:
        aliases:
          - api
networks:
  casa: